// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("ReactoKinesix.ExampleCs")]
[assembly: AssemblyProductAttribute("ReactoKinesix")]
[assembly: AssemblyDescriptionAttribute("A Rx-based .Net client library for Amazon Kinesis")]
[assembly: AssemblyVersionAttribute("0.6.0")]
[assembly: AssemblyFileVersionAttribute("0.6.0")]
[assembly: InternalsVisibleToAttribute("ReactoKinesiX.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.6.0";
    }
}
